#!/usr/bin/env python3
from pathlib import Path
import json
import sys


def c_ident(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch.upper())
        else:
            out.append("_")
    s = "".join(out)
    while "__" in s:
        s = s.replace("__", "_")
    return s.strip("_")


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_doc_assets.py <docs_dir> <out_header>")
        return 1

    docs_dir = Path(sys.argv[1])
    out_header = Path(sys.argv[2])
    component_dir = out_header.parent
    web_index = component_dir / "web" / "index.html"
    files = [
        "QUICK_WALKTHROUGH.md",
        "PROFILE_SCHEMA.md",
        "MACRO_STRUCTURE_DETAILED_GUIDE.md",
        "MACRO_WEB_UI_PLAN.md",
        "README.md",
    ]

    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("/* Auto-generated by tools/generate_doc_assets.py */")
    lines.append("")

    for fn in files:
        path = docs_dir / fn
        txt = path.read_text(encoding="utf-8")
        sym = c_ident(fn)
        cstr = json.dumps(txt, ensure_ascii=False)
        lines.append(f"static const char DOC_{sym}[] = {cstr};")
        lines.append(f"static const unsigned DOC_{sym}_LEN = (unsigned)(sizeof(DOC_{sym}) - 1);")
        lines.append("")

    if web_index.is_file():
        html = web_index.read_text(encoding="utf-8")
        lines.append(f"static const char WEB_INDEX_HTML[] = {json.dumps(html, ensure_ascii=False)};")
        lines.append("static const unsigned WEB_INDEX_HTML_LEN = (unsigned)(sizeof(WEB_INDEX_HTML) - 1);")
        lines.append("")

    out_header.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

