#!/usr/bin/env python3
from pathlib import Path
import json
import re
import sys


def c_ident(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch.upper())
        else:
            out.append("_")
    s = "".join(out)
    while "__" in s:
        s = s.replace("__", "_")
    return s.strip("_")


def slugify(title: str) -> str:
    t = title.strip().lower()
    t = re.sub(r"[^\w\s-]", "", t)
    t = re.sub(r"[\s_]+", "-", t)
    return t.strip("-")


def build_sidebar(md: str) -> str:
    """Docsify sidebar: profile-schema.md?id=<slug> (official single-page pattern)."""
    lines = ["- [Profile Schema](profile-schema.md)"]
    skip = {"table of contents"}
    for line in md.splitlines():
        if line.startswith("## "):
            title = line[3:].strip()
            if title.lower() in skip:
                continue
            lines.append(f"  - [{title}](profile-schema.md?id={slugify(title)})")
        elif line.startswith("### "):
            title = line[4:].strip()
            lines.append(f"    - [{title}](profile-schema.md?id={slugify(title)})")
    return "\n".join(lines) + "\n"


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_doc_assets.py <docs_dir> <out_header>")
        return 1

    docs_dir = Path(sys.argv[1])
    out_header = Path(sys.argv[2])
    component_dir = out_header.parent
    web_index = component_dir / "web" / "index.html"
    web_docs = component_dir / "web" / "docs.html"
    files = [
        "PROFILE_SCHEMA.md",
    ]

    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("/* Auto-generated by tools/generate_doc_assets.py */")
    lines.append("")

    profile_md = ""
    for fn in files:
        path = docs_dir / fn
        txt = path.read_text(encoding="utf-8")
        if fn == "PROFILE_SCHEMA.md":
            profile_md = txt
        sym = c_ident(fn)
        cstr = json.dumps(txt, ensure_ascii=False)
        lines.append(f"static const char DOC_{sym}[] = {cstr};")
        lines.append(f"static const unsigned DOC_{sym}_LEN = (unsigned)(sizeof(DOC_{sym}) - 1);")
        lines.append("")

    if profile_md:
        sidebar = build_sidebar(profile_md)
        cstr = json.dumps(sidebar, ensure_ascii=False)
        lines.append(f"static const char DOC_SIDEBAR_MD[] = {cstr};")
        lines.append("static const unsigned DOC_SIDEBAR_MD_LEN = (unsigned)(sizeof(DOC_SIDEBAR_MD) - 1);")
        lines.append("")

    if web_index.is_file():
        html = web_index.read_text(encoding="utf-8")
        lines.append(f"static const char WEB_INDEX_HTML[] = {json.dumps(html, ensure_ascii=False)};")
        lines.append("static const unsigned WEB_INDEX_HTML_LEN = (unsigned)(sizeof(WEB_INDEX_HTML) - 1);")
        lines.append("")
    if web_docs.is_file():
        html = web_docs.read_text(encoding="utf-8")
        lines.append(f"static const char WEB_DOCS_HTML[] = {json.dumps(html, ensure_ascii=False)};")
        lines.append("static const unsigned WEB_DOCS_HTML_LEN = (unsigned)(sizeof(WEB_DOCS_HTML) - 1);")
        lines.append("")

    out_header.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
