name: Build USB-Input (ESP32-S3)

on:
  push:
    branches: ["**"]
    paths:
      - "usb-input/**"
      - ".github/workflows/idf-usb-input.yml"
  pull_request:
    paths:
      - "usb-input/**"
      - ".github/workflows/idf-usb-input.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.1
          target: esp32s3
          path: usb-input
